import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:majdur_p/datamodel/receipts_datamodel.dart';
import 'dart:convert';

class FileReceipt extends StatelessWidget {
  final String rawJson;
  const FileReceipt({super.key, required this.rawJson});

  @override
  Widget build(BuildContext context) {
    final Map<String, dynamic>? jsonData = _parseJson(rawJson);
    if (jsonData == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Error')),
        body: const Center(child: Text('Invalid QR Code Data')),
      );
    }

    // Safe formatted date
    final String dateText = _formatDate(jsonData['date']);
    // Safe items string
    final String itemsText = jsonData['items']?.toString() ?? '—';
    // Safe value string
    final String valueText = jsonData['value']?.toString() ?? '—';

    return Scaffold(
      appBar: AppBar(title: const Text('Verify Receipt Data')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildDataRow(
              'ID',
              jsonData['id']?.toString() ?? 'Auto-generated by DB',
            ),
            _buildDataRow('Date', dateText),
            _buildDataRow('Items', itemsText),
            _buildDataRow('Value', valueText),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () => _uploadToSupabase(context, jsonData),
              child: const Text('Confirm & Upload'),
            ),
          ],
        ),
      ),
    );
  }

  Map<String, dynamic>? _parseJson(String rawJson) {
    try {
      final parsed = json.decode(rawJson);
      if (parsed is Map<String, dynamic>) return parsed;
      if (parsed is Map) {
        return Map<String, dynamic>.from(parsed);
      }
      return null;
    } catch (e) {
      return null;
    }
  }

  static String _formatDate(dynamic date) {
    if (date == null) {
      return 'Today (DB default)';
    }
    try {
      DateTime dt;
      if (date is int) {
        dt = DateTime.fromMillisecondsSinceEpoch(date);
      } else if (date is String) {
        dt = DateTime.parse(date);
      } else {
        return date.toString();
      }
      return DateFormat('yyyy-MM-dd').format(dt);
    } catch (e) {
      return date.toString();
    }
  }

  Widget _buildDataRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('$label: ', style: const TextStyle(fontWeight: FontWeight.bold)),
          Expanded(child: Text(value)),
        ],
      ),
    );
  }

  Future<void> _uploadToSupabase(
    BuildContext context,
    Map<String, dynamic> data,
  ) async {
    // Basic validation: items is required
    if (data['items'] == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Items field is required')));
      return;
    }

    try {
      // Show loading indicator
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (_) => const Center(child: CircularProgressIndicator()),
      );

      // Parse date if provided
      DateTime? parsedDate;
      if (data['date'] != null) {
        if (data['date'] is int) {
          parsedDate = DateTime.fromMillisecondsSinceEpoch(data['date']);
        } else if (data['date'] is String) {
          parsedDate = DateTime.tryParse(data['date']);
        }
      }

      // Create ReceiptDataModel
      final receipt = ReceiptDataModel(
        date: parsedDate,
        items: data['items'] is List
            ? List<String>.from(data['items'].map((e) => e.toString()))
            : [data['items'].toString()],
        value: data['value'] != null
            ? double.tryParse(data['value'].toString())
            : null,
      );

      // Insert into Supabase using ReceiptDataModel
      final insertedReceipt = await ReceiptDataModel.createReceipt(receipt);

      // Remove loading
      if (Navigator.canPop(context)) Navigator.pop(context);

      if (insertedReceipt != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              'Receipt uploaded successfully! ID: ${insertedReceipt['id']}',
            ),
          ),
        );
        if (Navigator.canPop(context)) Navigator.pop(context);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Upload completed (no data returned)')),
        );
        if (Navigator.canPop(context)) Navigator.pop(context);
      }
    } catch (e) {
      // Remove loading
      if (Navigator.canPop(context)) Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error uploading: ${e.toString()}')),
      );
      debugPrint('Supabase upload error: $e');
    }
  }
}
